### ISSUE TITLE
Making sure references are indexable by Google Scholar

### ISSUE THREAD

**Issue by chartgerink** [hypergraph-xyz/editor#2]
Google Scholar has a parser that deals with references, and I'm adding this issue to make sure our editor is parsable by Google Scholar so our Hypergraph Vault content will rank higher and with more information for the end-users. See also the wiki of the [Hypergraph Vault](https://github.com/hypergraph-xyz/vault/wiki/Google-Scholar).

> Mark the section of the paper that contains references to other works with a standard heading, such as "References" or "Bibliography", on a line just by itself. Individual references inside this section should be either numbered "1. - 2. - 3." or "[1] - [2] - [3]" in PDF, or put inside an "\<ol\>" list in HTML. The text of each reference must be a formal bibliographic citation in a commonly used format, without free-form commentary.

> Please understand that the references are identified automatically by the parser software; they're not entered or corrected by human operators. While we try to support the most common reference formats, it is not possible to guarantee that all references are identified correctly; and incorrect identification of references could lead to exclusion of your papers from Google Scholar or to low ranking of your papers in the search results.

**Comment by juliangruber** [comment]
Marking as blocked as the editor technology we're using isn't ready for this kind of integration yet
